export const chatData = [
  {
    name: 'Erdem',
    src: 'https://randomuser.me/api/portraits/men/52.jpg',
    message: 'tamamdır. belgeleri sana gönderiyorum.',
    date: '16:20',
    seen: true,
  },
  {
    name: 'Babam',
    src: 'https://randomuser.me/api/portraits/men/21.jpg',
    message: 'Akşam amcanlara gidiyoruz. Gelecek misin?',
    date: '16:15',
    seen: false,
  },
  {
    name: 'Annem',
    src: 'https://randomuser.me/api/portraits/women/7.jpg',
    message: 'İlaçlarını içmeyi unutma sakın',
    date: 'Pazartesi',
    seen: true,
  },
  {
    name: 'Abim',
    src: 'https://randomuser.me/api/portraits/men/24.jpg',
    message: 'Çok teşekkür ederim.',
    date: 'Perşembe',
    seen: true,
  },
  {
    name: 'Harun',
    src: 'https://randomuser.me/api/portraits/men/34.jpg',
    message: '📷 Ben ne alaka',
    date: 'Cuma',
    seen: true,
  },
  {
    name: 'Mehmet',
    src: 'https://randomuser.me/api/portraits/men/6.jpg',
    message: '📄 ust-veraset-belge.pdf.pdf • 1 sayfa',
    date: 'Cuma',
    seen: true,
  },
  {
    name: 'Ayşe',
    src: 'https://randomuser.me/api/portraits/women/17.jpg',
    message: 'Tamam yarın görüşürüz.',
    date: 'Çarşamba',
    seen: false,
  },
  {
    name: 'İrem',
    src: 'https://randomuser.me/api/portraits/women/51.jpg',
    message: 'İyi bayramlar 💗🥺🥺🥺',
    date: 'Çarşamba',
    seen: false,
  },
  {
    name: 'Münir',
    src: 'https://randomuser.me/api/portraits/men/41.jpg',
    message: 'tamamdır. teşekkür ederim',
    date: '19.04.2023',
    seen: false,
  },
  {
    name: 'Taksi',
    src: '',
    message: "Tip için teşekkürler",
    date: '17.04.2023',
    seen: true,
  },
  {
    name: 'Restaurant',
    src: '',
    message: 'Eksiksiz gönderim için teşekkürler.',
    date: '16.04.2023',
    seen: true,
  },
  {
    name: 'Harun',
    src: 'https://randomuser.me/api/portraits/men/3.jpg',
    message: 'iyimiş bu',
    date: '15.04.2023',
    seen: false,
  },
];